name: projeto_tcc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  flutter_svg: ^0.23.0+1
  flutter_flavorizr: ^2.0.0
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  get: ^4.3.8
  responsive_sizer: 3.0.4+4
  rounded_loading_button: ^2.0.9
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3
  uuid: ^3.0.5
  carousel_slider: ^4.0.0
  im_stepper: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    dev:
      app:
        name: "PCE DEV"
      android:
        applicationId: "com.trabalhotcc.prototipo_controle_educacional_dev"
      ios:
        bundleId: "com.trabalhotcc.prototipo_controle_educacional_dev"
    hmlg:
      app:
        name: "PCE HMLG"
      android:
        applicationId: "com.trabalhotcc.prototipo_controle_educacional_hmlg"
      ios:
        bundleId: "com.trabalhotcc.prototipo_controle_educacional_hmlg"
    prod:
      app:
        name: "PCE"
      android:
        applicationId: "com.trabalhotcc.prototipo_controle_educacional"
      ios:
        bundleId: "com.trabalhotcc.prototipo_controle_educacional"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/app/assets/images/
    - lib/app/assets/svgs/