name: projeto_tcc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.6
  get: ^4.6.3
  uuid: ^3.0.6
  intl: ^0.17.0
  pinput: ^2.2.9
  shimmer: ^2.0.0
  sqflite: ^2.0.2+1
  im_stepper: ^1.0.0
  flutter_svg: ^1.0.3
  reorderables: ^0.5.0
  bottom_sheet: ^3.1.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  responsive_sizer: ^3.0.8
  flutter_flavorizr: ^2.1.3
  font_awesome_flutter: ^10.1.0
  rounded_loading_button: ^2.1.0
  mask_text_input_formatter: ^2.3.0
  syncfusion_flutter_calendar: ^20.1.56

dev_dependencies:
  flutter_test:
    sdk: flutter

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    dev:
      app:
        name: "PCE DEV"
      android:
        applicationId: "com.trabalhotcc.prototipo_controle_educacional_dev"
      ios:
        bundleId: "com.trabalhotcc.prototipo_controle_educacional_dev"
    hmlg:
      app:
        name: "PCE HMLG"
      android:
        applicationId: "com.trabalhotcc.prototipo_controle_educacional_hmlg"
      ios:
        bundleId: "com.trabalhotcc.prototipo_controle_educacional_hmlg"
    prod:
      app:
        name: "PCE"
      android:
        applicationId: "com.trabalhotcc.prototipo_controle_educacional"
      ios:
        bundleId: "com.trabalhotcc.prototipo_controle_educacional"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/app/assets/images/
    - lib/app/assets/svgs/